project_id = "ClassMate"

[auth.third_party.firebase]
enabled = true
project_id = "classmate-a016a"

[functions.send-notification]
verify_jwt = false

[functions.dispatch-classmate-notifications]
verify_jwt = false

[functions.publish-classmate-release]
verify_jwt = false

[functions.cleanup-classmate-resources]
verify_jwt = false
