import type { Metadata } from "next";
import Link from "next/link";
import PublicPage, { supportEmail } from "@/components/public-page";

export const metadata: Metadata = { title: "Terms of Service | ClassMate", description: "Terms for using ClassMate’s academic and community services." };

export default function TermsPage() {
  return <PublicPage policy title="Terms of Service" lead="Please read these terms before using ClassMate’s web or Android services.">
    <section><h2>1. The service</h2><p>ClassMate is an independent academic and community application developed by Mohammad Shuaib-Ud-Dowla for the MBSTU community. It is not an official university authority. By using ClassMate, you agree to these terms and acknowledge our <Link href="/privacy">Privacy Policy</Link>.</p></section>
    <section><h2>2. Accounts and access</h2><p>Students must use their eligible university account. Teachers must use an administrator-approved email and assigned classroom access. Provide accurate information, protect your Google account and do not impersonate others. Access depends on backend verification, batch membership and assigned roles.</p><p>Permissions to post or manage content are limited to your authorized scope. Approval does not grant access to other batches or private information outside that scope.</p></section>
    <section><h2>3. Respectful and lawful use</h2><p>Do not harass others, post misleading emergencies, send spam, upload malicious files, bypass access controls, scrape private contact information or attempt to compromise the service. Use personal information only for its intended academic or community purpose. Accounts or content may be restricted when necessary to protect users or address misuse.</p></section>
    <section><h2>4. Content and learning resources</h2><p>You retain rights to content you contribute. You give ClassMate permission to store, process and display it to authorized users as needed to operate the service. Upload only materials you have permission to share, and obtain permission before sharing another person’s private details.</p><p>Download access does not transfer copyright or authorize redistribution. Report inappropriate content or copyright concerns to the support address below.</p></section>
    <section><h2>5. Academic information and AI</h2><p>Timetables, notices, calendars and bus information depend on contributions and published sources. Verify important changes with your teacher or university. AI can make mistakes; review generated notices, translations and proposed changes. AI features are intended for users aged 18 or older and must not be used for clinical or medical advice.</p><p>Notification delivery depends on device permission, internet access and provider availability. ClassMate does not guarantee that every alert arrives or is read.</p></section>
    <section><h2>6. Blood requests and emergencies</h2><p>The blood network helps people coordinate requests and contact potential donors. A blood-group match or availability filter does not establish medical eligibility or safety. Donation and transfusion decisions must be made by qualified medical professionals. Contact the hospital or local emergency services directly when urgent care is needed; do not rely on ClassMate alone.</p><p>Requesters are responsible for accurate contact, location and timing details and for permission to share those details. Volunteers decide whether to respond.</p></section>
    <section><h2>7. Availability, updates and external services</h2><p>The service may change, be interrupted or become unavailable. Keep independent copies of important resources. Google, Supabase, Firebase, Gemini, Cloudflare, Vercel and linked third-party services have their own terms. Android downloads and installation are also subject to your device’s permissions and confirmation.</p><p>ClassMate is provided as available, without a promise of uninterrupted or error-free operation. Nothing in these terms removes rights or responsibilities that cannot be excluded under applicable law.</p></section>
    <section><h2>8. Leaving, changes and contact</h2><p>You can stop using ClassMate or sign out at any time. For account deletion, privacy requests, abuse reports or support, contact <a href={`mailto:${supportEmail}`}>{supportEmail}</a>. We may verify your identity before changing account data.</p><p>Revised terms will be published here with an updated effective date. Review this page when using newly introduced features.</p></section>
  </PublicPage>;
}
